version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - target: 5000
              published: 5000
              protocol: tcp
        labels:
            - "autoheal=true"
        healthcheck:
            test: curl --fail http://localhost:5000/ || exit 1
            interval: 40s
            timeout: 30s
            retries: 3
            start_period: 60s

    autoheal:
        image: willfarrell/autoheal:latest
        tty: true
        restart: always
        environment:
            - AUTOHEAL_INTERVAL=60
            - AUTOHEAL_START_PERIOD=300
            - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
